default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_backend_development

test:
  <<: *default
  database: ecommerce_backend_test

production:
  <<: *default
  database: ecommerce_backend_production
  username: ecommerce_backend
  password: <%= ENV['ECOMMERCE_BACKEND_DATABASE_PASSWORD'] %>
